CAUCA-9-1-1/survip

src/app/intervention-plan/intervention-layer/intervention-layer.directive.spec.ts
src/app/intervention-plan/intervention-layer/intervention-layer.directive.ts
src/app/intervention-plan/intervention-plan.module.ts
src/app/intervention-plan/shared/intervention.service.spec.ts
src/app/intervention-plan/shared/intervention.service.ts
src/app/pages/intervention/maps/maps.component.html
src/contexts/_default.json

- Intervention service that constains dummy data
- Intervention layer is not of the vector type and can be added to a map with a directive

feat(intervention): intervention layer is now of the vector type

---

src/app/auth-guard.service.ts
src/app/intervention-maps/intervention-layer/intervention-layer.directive.ts
src/app/shared/components/take-picture/take-picture.component.ts
src/app/shared/services/window-ref.service.ts
src/contexts/_default.json

Add mock to all inspection
Show inspection on the map
Add click on every inspection

Pre75 mock inspection

---

src/app/intervention-maps/intervention-layer/intervention-layer.directive.ts
src/app/intervention-maps/intervention-maps.component.ts
src/app/intervention-maps/intervention-maps.module.ts
src/app/intervention-survey/building/building.component.html
src/app/intervention-survey/building/building.component.ts
src/app/intervention-survey/course-lane/course-lane.component.html
src/app/intervention-survey/course-lane/course-lane.component.spec.ts
src/app/intervention-survey/course-lane/course-lane.component.ts
src/app/intervention-survey/course/course.component.html
src/app/intervention-survey/course/course.component.spec.ts
src/app/intervention-survey/course/course.component.styl
src/app/intervention-survey/course/course.component.ts
src/app/intervention-survey/implantation-plan/implantation-plan.component.ts
src/app/intervention-survey/intervention-survey.module.ts
src/app/intervention-survey/shared/models/firestation.ts
src/app/intervention-survey/shared/models/intervention-plan-course-lane.ts
src/app/intervention-survey/shared/models/intervention-plan-course.ts
src/app/intervention-survey/shared/services/firestation.service.spec.ts
src/app/intervention-survey/shared/services/firestation.service.ts
src/app/intervention-survey/shared/services/intervention-plan-course-lane.service.spec.ts
src/app/intervention-survey/shared/services/intervention-plan-course-lane.service.ts
src/app/intervention-survey/shared/services/intervention-plan-course.service.spec.ts
src/app/intervention-survey/shared/services/intervention-plan-course.service.ts
src/app/mockdata/firestation-data.ts
src/app/mockdata/in-memory-data.service.ts
src/app/mockdata/intervention-plan-course-data.ts
src/app/mockdata/intervention-plan-course-lane-data.ts
src/app/shared/services/picture.service.ts
src/assets/locale/fr.json
src/styles.styl

Show all course of one intervention plan
Fix the click on feature off map

Pre67 plan course

---

src/app/intervention-survey/building/building.component.ts
src/app/intervention-survey/shared/services/intervention-plan-course.service.ts
src/app/mockdata/intervention-plan-course-data.ts

Load all course for only one specific intervention plan

(fix) Load course for only one intervention plan

---

src/app/intervention-maps/intervention-layer/intervention-layer.directive.ts
src/app/intervention-maps/intervention-maps.component.ts
src/app/intervention-maps/intervention-maps.module.ts
src/app/intervention-maps/shared/intervention.service.ts
src/app/prevention-survey/prevention-survey.component.html
src/app/prevention-survey/prevention-survey.component.ts
src/app/shared/components/take-picture/take-picture.component.html
src/app/shared/interfaces/inspection.interface.ts
src/app/shared/services/inspection.service.ts
src/contexts/contexts.json
src/contexts/default.json

Don't show image if source is not set

Pre 123 picture service

---

src/app/prevention-survey/prevention-survey.component.ts
src/app/prevention-survey/question-slider/question-slider.component.html
src/app/prevention-survey/question-slider/question-slider.component.ts

Let user to go back on prevention survey

(feat) Add a previous button on prevention survey

---

src/app/mockdata/building-data.ts
src/app/mockdata/in-memory-data.service.ts
src/app/prevention-survey/prevention-survey.component.ts
src/app/shared/interfaces/building.interface.ts
src/app/shared/services/building.service.spec.ts
src/app/shared/services/building.service.ts

Show the address on toolbar of prevention survey

(feat) Show the address on toolbar

---

src/app/shared/components/fullscreen-dialog/fullscreen-dialog.component.html
src/app/shared/components/fullscreen-dialog/fullscreen-dialog.component.spec.ts
src/app/shared/components/fullscreen-dialog/fullscreen-dialog.component.styl
src/app/shared/components/fullscreen-dialog/fullscreen-dialog.component.ts
src/app/shared/components/take-picture/take-picture.component.html
src/app/shared/directives/pinch-zoom.directive.spec.ts
src/app/shared/directives/pinch-zoom.directive.ts
src/app/shared/services/dialogs.service.ts
src/app/shared/shared.module.ts
src/styles.styl

Create a directive to open dialog when user click on a image

Pre112 pinchzoom

---

cordova/config.xml
src/app/prevention-survey/question-slider/question-slider.component.ts
src/index.html

Add a portrait image for the angular splashscreen

(fix) Add angular splashscreen for portrait

---

cordova/config.xml
package.json
src/app/shared/directives/pinch-zoom.directive.ts

Add pinch zoom on popup of take-picture component

(feat) Add pinch zoom on popup of take-picture component

---

src/app/app-routing.ts
src/app/management-survey/list/list.component.html
src/app/management-survey/list/list.component.ts
src/app/management-survey/question/question.component.html
src/app/management-survey/question/question.component.styl
src/app/management-survey/question/question.component.ts
src/app/management-survey/shared/models/choice.model.ts
src/app/management-survey/shared/models/question.model.ts
src/app/management-survey/shared/models/survey.model.ts
src/app/management-survey/shared/services/choice.service.ts
src/app/management-survey/shared/services/question.service.ts
src/app/management-survey/shared/services/survey.service.ts
src/app/shared/classes/grid-with-crud-service.ts
src/app/shared/components/multilang/multilang.component.html
src/app/shared/components/multilang/multilang.component.ts
src/app/shared/models/with-localization.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

#75 refactor survey with api

---

src/app/inspection-approval/building-details/building-details.component.ts
src/app/inspection-approval/contacts/contacts.component.html
src/app/inspection-approval/contacts/contacts.component.ts
src/app/inspection-approval/course/course.component.html
src/app/inspection-approval/course/course.component.ts
src/app/inspection-approval/fire-protection/fire-protection.component.html
src/app/inspection-approval/fire-protection/fire-protection.component.ts
src/app/inspection-approval/hazardous-materials/hazardous-materials.component.html
src/app/inspection-approval/hazardous-materials/hazardous-materials.component.ts
src/app/inspection-approval/inspection-approval.component.html
src/app/inspection-approval/inspection-approval.component.scss
src/app/inspection-approval/pnaps/pnaps.component.html
src/app/inspection-approval/pnaps/pnaps.component.ts
src/app/inspection-approval/water-supply/water-supply.component.html
src/app/inspection-approval/water-supply/water-supply.component.ts
src/app/inspection-dashboard/shared/services/inspection.service.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Ce pull request inclut #101 et #102 
Faire le pull request #117 avant

#101 consultation bornes

---

src/app/inspection-approval/inspection-approval.component.html
src/app/inspection-approval/inspection-approval.component.scss
src/app/inspection-approval/survey/survey.component.html
src/app/inspection-approval/survey/survey.component.ts
src/app/inspection-dashboard/shared/services/inspection.service.ts

Doit avoir la branche #45_resume_reponses_questionnaire de l'API

#95 consultation questionnaire

---

src/app/app.module.ts
src/app/inspection-approval/inspection-general-info/inspection-general-info.component.ts
src/app/inspection-dashboard/inspection-dashboard.component.ts
src/app/inspection-management/inspection-management.component.ts
src/app/management-address/shared/services/lane.service.ts
src/app/management-building/hazardous-material/hazardous-material.component.html
src/app/management-building/hazardous-material/hazardous-material.component.ts
src/app/management-building/list/list.component.html
src/app/management-building/list/list.component.ts
src/app/management-building/management-building.component.html
src/app/management-building/management-building.module.ts
src/app/management-building/person-requiring-assistance-type/person-requiring-assistance-type.component.html
src/app/management-building/person-requiring-assistance-type/person-requiring-assistance-type.component.ts
src/app/management-building/risk-level/risk-level.component.html
src/app/management-building/risk-level/risk-level.component.ts
src/app/management-building/shared/models/building.model.ts
src/app/management-building/shared/models/hazardous-material.model.ts
src/app/management-building/shared/models/person-requiring-assistance-type.model.ts
src/app/management-building/shared/services/building.service.ts
src/app/management-building/shared/services/hazardous-material.service.ts
src/app/management-building/shared/services/person-requiring-assistance-type.service.ts
src/app/management-building/shared/services/risk-level.service.ts
src/app/management-building/shared/services/utilisation-code.service.ts
src/app/management-building/utilisation-code/utilisation-code.component.html
src/app/management-building/utilisation-code/utilisation-code.component.ts
src/app/shared/classes/grid-with-crud-service.ts
src/app/shared/models/base.model.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Faire le pull request #143 avant celui-ci

#78 building child

---

src/app/inspection-approval/shared/services/inspection-building-pnaps.service.spec.ts
src/app/inspection-approval/shared/services/inspection-building-pnaps.service.ts
src/app/management-building/list/list.component.html
src/app/management-building/list/list.component.ts
src/app/management-building/manage-pnaps/manage-pnaps.component.html
src/app/management-building/manage-pnaps/manage-pnaps.component.spec.ts
src/app/management-building/manage-pnaps/manage-pnaps.component.ts
src/app/management-building/management-building.module.ts
src/app/management-building/shared/models/building-pnaps.model.ts
src/app/management-building/shared/services/building-pnaps.service.spec.ts
src/app/management-building/shared/services/building-pnaps.service.ts
src/app/management-building/shared/services/person-requiring-assistance-type.service.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Faire le pull request #151 avant celui-ci

#79 building pnaps

---

src/app/management-survey/question/question.component.html
src/app/management-survey/question/question.component.scss
src/app/management-survey/question/question.component.ts
src/app/management-survey/shared/models/question.model.ts
src/app/management-survey/shared/services/question.service.ts
src/app/shared/components/multilang/multilang.component.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Do the #113 in webAPI first
Manage Parent/Child structure to the survey questions

#221 new survey structure

---

src/app/inspection-approval/inspection-survey/inspection-survey.component.html

Use group of question for recursive ones

feat(#181) Adapt survey summary to new survey structure

---

package-lock.json
package.json

Alignement temporaire à gauche du canvas dans la fenêtre d'édition de croquis selon la demande de Jocelyn.

feat(#290): Left alignment on open to prevent issues

---

src/app/inspection-dashboard/inspection-dashboard.component.ts

Add digits and value changing validation on :
- numberOfAppartment
- numberOfBuilding
- numberOfFloor
- yearOfConstruction

#316 number field validation

---

package-lock.json
package.json
src/app/shared/components/image/image.component.ts

Ajustement du rectancle lors de la sélection pour le crop et reload du croquis coupé.

#294 sketch crop

---

src/app/management-survey/list/list.component.html
src/app/management-survey/list/list.component.ts
src/app/management-survey/shared/services/survey.service.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Please do the web-Api pull request #361 first.

feat(#361) Add duplicate option for survey

---

src/app/app.module.ts
src/app/shared/shared.module.ts

Attention, va avec un pull request dans SURVIP-WEBAPI

Feaet(#365) Move http interceptor from one of the shared module to app.module.

---

src/app/app.component.spec.ts
src/app/inspection-batch/inspection-batch.component.ts
src/app/inspection-batch/shared/services/inspection-batch.service.ts
src/app/shared/classes/grid-with-crud-service.ts

Fix(#359) Only load the wanted batch when editing one batch.

---

src/app/inspection-batch/inspection-batch.component.ts
src/app/inspection-dashboard/inspection-dashboard.component.ts
src/app/management-department/building/building.component.ts
src/app/management-department/firehydrant/firehydrant.component.ts
src/app/management-department/lane/lane.component.ts
src/app/shared/models/o-data-config.model.ts
src/app/shared/services/expired-token.interceptor.ts
src/app/shared/services/o-data.service.ts

+ web api.
console is still showing a weird error when the refreshToken become expired (after 9 hours), but it seems there's no consequence at all from that error.

#381 authentification issues odata etc

---

src/app/inspection-batch/inspection-batch.component.html
src/app/inspection-batch/inspection-batch.component.scss
src/app/inspection-batch/inspection-batch.component.ts
src/app/inspection-batch/inspection-batch.module.ts
src/app/inspection-dashboard/inspection-dashboard.component.html
src/app/inspection-dashboard/inspection-dashboard.component.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Check the web-Api pull request #185 first.

feat(#370) Add status delete validation on batch and inspection

---

package.json
src/app/shared/components/image/image.component.ts

Modifications pour enregistrer l'image dans la même résolution que l'image d'origine.

#291 sketch saving quality

---

package.json

Ajout du undo pour la fontion de crop.

feat(#410): Updated library to include undo

---

src/app/app-routing.ts
src/app/inspection-dashboard/inspection-dashboard.component.ts
src/app/shared/components/image/image.component.ts
src/app/shared/services/picture.service.ts
src/app/user-access/login/login.component.ts
src/app/user-access/shared/models/configuration.model.ts
src/app/user-access/shared/services/configuration.service.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Check the web-api pull request first(#232)

feat(#413) validation picture size to send to api

---

src/app/report-configuration/select-template/select-template.component.html
src/app/report-configuration/select-template/select-template.component.ts
src/app/shared/services/report-template.service.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Permet la duplication d'un template de rapport (similaire à la fonction déjà présente pour les questionnaires).

#427 report duplicate

---

src/app/management-system/department/department.component.html
src/app/management-system/shared/models/firesafetydepartment.model.ts

Do the web-api pull request first

feat(#243) Add picture to fire safety department

---

src/app/inspection-dashboard/inspection-dashboard.component.html
src/app/inspection-dashboard/inspection-dashboard.component.ts
src/app/report-configuration/select-template/select-template.component.html
src/app/report-configuration/select-template/select-template.component.ts
src/app/shared/models/configuration-template.model.ts
src/app/shared/services/report-template.service.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Permettre de sélectionner le SSI du rapport lors de la création ou modification
Permettre de dire qu'un rapport est celui par défaut ou non pour un SSI (un seul par SSI)

#420 report ssi

---

src/app/shared/components/main-menu/main-menu.component.html
src/app/shared/components/main-menu/main-menu.component.scss
src/app/shared/components/main-menu/main-menu.component.ts
src/app/user-access/login/login.component.html
src/app/user-access/login/login.component.scss
src/app/user-access/login/login.component.ts
src/assets/i18n/en.json
src/assets/i18n/fr.json

Affiche la version dans le menu et sur la page de login.

#280 show version

---

package-lock.json
package.json
src/app/inspection-approval/inspection-water-supply/inspection-water-supply.component.ts
src/app/management-department/firehydrant/firehydrant.component.html
src/app/management-department/firehydrant/firehydrant.component.scss
src/app/management-department/firehydrant/firehydrant.component.ts
src/app/management-department/shared/models/fire-hydrant.model.ts
src/app/management-type-system/shared/services/location-type.service.ts
src/assets/config/config.json
src/assets/i18n/en.json
src/assets/i18n/fr.json

Modify dynamic display of the locations controls

#415 fire hydrant with dx template

---

package-lock.json
src/app/management-department/building/building.component.html
src/app/management-department/building/building.component.ts
src/app/management-department/firehydrant/firehydrant.component.html
src/app/management-department/firehydrant/firehydrant.component.ts
src/app/management-department/lane/lane.component.html
src/app/management-department/lane/lane.component.ts
src/app/management-department/manage-contacts/manage-contacts.component.ts
src/app/management-department/manage-hazardous-material/manage-hazardous-material.component.ts
src/app/management-department/manage-pnaps/manage-pnaps.component.ts
src/app/management-department/management-department.component.scss
src/app/management-department/shared/models/building.model.ts
src/app/shared/classes/grid-with-crud-service.ts
src/app/shared/classes/grid-with-odata-service.ts
src/app/shared/services/request.service.ts
src/assets/config/config.json

Please do the web-api pullrequest first #296

#476 add building child doesnt work
